#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn workspace my-react tsc
yarn workspace my-react lint
yarn workspace my-react test
yarn workspace my-react build
yarn workspace app lint
yarn workspace app tsc
yarn workspace my-react cleanup
